"""Generate scanned_table_scene.xml from the curated scanned-object params.

Each object: scanned mesh as the VISUAL (centered at the body origin), a simple
BOX collision (reliable top-down grasp), a free joint, and both arms' grasp welds.
Objects are spread across the large bimanual table; two grey bins on the sides.
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
P = json.load(open(os.path.join(ROOT, "_scanned_params.json")))
TABLE_TOP = 0.40

# (name, x, y) on the large table -- spread, clear of the bins and of both raised
# arms' top-down camera shadows (|y| <= ~0.20).
LAYOUT = [
    ("mug",      0.20,  0.20),
    ("elephant", 0.32,  0.06),
    ("bowl",     0.32, -0.06),
    ("clock",    0.20, -0.20),
]

HEAD = '''<!--
Copyright 2026 Enactic, Inc.
Licensed under the Apache License, Version 2.0 (the "License").
Scanned-object interactive table (Phase I): real Google Scanned Objects on a
large bimanual table. Each object's VISUAL is the scanned mesh (scaled to a
graspable size and centred); its COLLISION is a simple box (reliable top-down
grasp). Detected by the open-vocabulary detector (YOLO-World / YOLOE); the
interactive playground lists them and the dual-arm coordinator manipulates them.
Auto-generated by gen_scanned_scene.py.
-->
<mujoco model="openarm_v20_scanned_table">
  <compiler meshdir="assets" texturedir="assets" angle="radian"/>
  <default>
    <default class="visual"><geom contype="0" conaffinity="0" group="2"/></default>
    <default class="collision"><geom condim="3" conaffinity="1" priority="1" group="3" solref="0.005 1" friction="1 0.01 0.01"/></default>
  </default>
  <statistic center="0.28 0 0.55" extent="1.4" meansize="0.05"/>
  <option timestep="0.002"/>
  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.4 0.4 0.4" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/><global azimuth="150" elevation="-20" offwidth="1280" offheight="960"/><quality shadowsize="8192"/>
  </visual>
  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.55 0.55 0.58" rgb2="0.2 0.2 0.2" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.38 0.38 0.4" rgb2="0.3 0.3 0.32" markrgb="0.6 0.6 0.6" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
    <mesh name="body_link0" content_type="model/stl" file="visual/body/body_link0.stl" scale="0.001 0.001 0.001"/>
    <mesh name="body_link0_symp" content_type="model/stl" file="collision/body_link0_symp.stl" scale="0.001 0.001 0.001"/>
    <model name="bimanual" file="openarm_v20_bimanual.xml"/>
'''

BIN = '''    <body name="{nm}" pos="{x} {y} 0.40">
      <geom name="{nm}_floor" type="box" size="0.07 0.07 0.01" pos="0 0 0.01" rgba="0.45 0.45 0.5 1" contype="1" conaffinity="1"/>
      <geom name="{nm}_n" type="box" size="0.07 0.008 0.035" pos="0 0.07 0.035" rgba="0.45 0.45 0.5 1" contype="1" conaffinity="1"/>
      <geom name="{nm}_s" type="box" size="0.07 0.008 0.035" pos="0 -0.07 0.035" rgba="0.45 0.45 0.5 1" contype="1" conaffinity="1"/>
      <geom name="{nm}_e" type="box" size="0.008 0.07 0.035" pos="0.07 0 0.035" rgba="0.45 0.45 0.5 1" contype="1" conaffinity="1"/>
      <geom name="{nm}_w" type="box" size="0.008 0.07 0.035" pos="-0.07 0 0.035" rgba="0.45 0.45 0.5 1" contype="1" conaffinity="1"/>
    </body>
'''


def main():
    s = HEAD
    # per-object mesh + material assets
    for name in P:
        sc = P[name]["scale"]
        s += f'    <texture type="2d" name="{name}_tex" file="scanned/{name}/{name}.png"/>\n'
        s += f'    <material name="{name}_mat" texture="{name}_tex" specular="0.3" shininess="0.3"/>\n'
        s += f'    <mesh name="{name}_mesh" file="scanned/{name}/{name}.obj" scale="{sc} {sc} {sc}"/>\n'
    s += '  </asset>\n\n  <worldbody>\n'
    s += '    <light pos="0 0 2" dir="0 0 -1" directional="true"/>\n'
    s += '    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>\n'
    s += '    <camera name="tablecam" pos="0.28 0.0 1.45" xyaxes="1 0 0 0 1 0" fovy="62"/>\n'
    s += '    <camera name="frontcam" pos="1.10 0.0 0.9" xyaxes="0 -1 0 0.3 0 1" fovy="58"/>\n'
    s += '    <geom name="openarm_body_link0_visual" type="mesh" mesh="body_link0" class="visual" material="openarm_body_link0_material"/>\n'
    s += '    <geom name="openarm_body_link0_collision" type="mesh" mesh="body_link0_symp" class="collision"/>\n'
    s += '    <frame pos="0 0 0.698"><attach model="bimanual" prefix=""/></frame>\n'
    s += '    <body name="table" pos="0.28 0.0 0.36">\n'
    s += '      <geom name="table_top" type="box" size="0.22 0.45 0.04" rgba="0.82 0.71 0.55 1" friction="1 0.005 0.0001" contype="1" conaffinity="1"/>\n    </body>\n'

    qpos_obj = []
    for name, x, y in LAYOUT:
        cx, cy, cz = P[name]["center"]
        hx, hy, hz = P[name]["half"]
        z = TABLE_TOP + hz
        s += f'    <body name="{name}" pos="{x} {y} {z:.4f}"><freejoint/>\n'
        s += (f'      <geom name="{name}_vis" type="mesh" mesh="{name}_mesh" material="{name}_mat" '
              f'pos="{-cx:.4f} {-cy:.4f} {-cz:.4f}" contype="0" conaffinity="0" group="2"/>\n')
        s += (f'      <geom name="{name}_col" type="box" size="{hx:.4f} {hy:.4f} {hz:.4f}" '
              f'mass="0.05" rgba="0.5 0.5 0.5 0" contype="1" conaffinity="1"/>\n')
        s += '    </body>\n'
        qpos_obj.append(f"{x} {y} {z:.4f} 1 0 0 0")

    s += BIN.format(nm="bin_left", x=0.30, y=0.36)
    s += BIN.format(nm="bin_right", x=0.30, y=-0.36)
    s += '  </worldbody>\n\n  <equality>\n'
    for name, _, _ in LAYOUT:
        s += f'    <weld name="grasp_right_{name}" body1="openarm_right_ee_base_link" body2="{name}" active="false" solref="0.02 1"/>\n'
        s += f'    <weld name="grasp_left_{name}" body1="openarm_left_ee_base_link" body2="{name}" active="false" solref="0.02 1"/>\n'
    s += '  </equality>\n\n  <keyframe>\n'
    # both arms start raised (left = joint-space mirror of the right) so neither hits the table
    arms = ("0.720369 -2.27095 -0.290977 1.90389 -1.23759 -0.785149 -0.558776 0 0\n"
            "            -0.720369 2.27095 0.290977 1.90389 1.23759 0.785149 0.558776 0 0")
    s += f'    <key name="ready" qpos="{arms}\n            ' + "\n            ".join(qpos_obj) + '"/>\n'
    s += '  </keyframe>\n</mujoco>\n'

    out = os.path.join(ROOT, "v2", "openarm_mujoco_v2", "scanned_table_scene.xml")
    open(out, "w", encoding="utf-8").write(s)
    print("wrote", out)


if __name__ == "__main__":
    main()
